### ISSUE TITLE
Implement backend

### ISSUE THREAD

**Issue by MaxMuecket** [MaxMuecket/pocket-garden#24]
#### Description

Implement backend

#### Tasks

- [ ] Add MongoDB
- [ ] Add Connect to MongoDB
- [ ] Add proxy to API

- [ ] Insert new plants
- [ ] Find plants
- [ ] Delete plants

- [ ] Insert new Tasks
- [ ] Find Tasks
- [ ] Delete Tasks
