### ISSUE TITLE
side menu bar

### ISSUE THREAD

**Issue by MaxMuecket** [MaxMuecket/pocket-garden#25]
#### Description

For the navigation between the Web-App pages.

#### Screenshots

![image](https://user-images.githubusercontent.com/82370293/123259708-10458680-d4f5-11eb-9f9c-dae5902b9941.png)

#### Tasks

- [ ] Add SideMenu component
- [ ] Implement PageLink component
- [ ] Implement SideMenu component to Web-App pages
