### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by MaxMuecket** [MaxMuecket/pocket-garden#3]
#### Description

This is the first page of the web app "Pocket-Garden" 
and the only function on the page is to bring the user by touch/click on the title to the main page.

#### Screenshots

![image](https://user-images.githubusercontent.com/82370293/121874940-276fc180-cd08-11eb-99e4-d2ec0a7fd5a8.png)

#### Tasks

`Components`

- [x] Subtitle link `<a>`Pocket-Garden`</a>` 

Page

- [x] Add background image

CSS

- [x] Create Global variables

   Global variables (global.css):

   - [x] --baground-color: #E9EFED;
   - [x] --primary-color: #334338;
   - [x] --secondary-color: #90A686;
   - [x] --primary-text-color: #000000;
   - [x] --secondary-text-color: #FFFFFF;
   - [x] --font-family: 'Roboto', sans-serif;
