### ISSUE TITLE
Design of the web app

### ISSUE THREAD

**Issue by MaxMuecket** [MaxMuecket/pocket-garden#4]
#### Description

Design improving and finding navigation solutions.

#### Screenshots

![image](https://user-images.githubusercontent.com/82370293/121499492-bc5b7d80-c9dd-11eb-960b-e885ba28e435.png)

![image](https://user-images.githubusercontent.com/82370293/121499552-c9786c80-c9dd-11eb-8e54-2c9e489a8964.png)

![image](https://user-images.githubusercontent.com/82370293/121499581-d09f7a80-c9dd-11eb-918e-5765912e27c9.png)

![image](https://user-images.githubusercontent.com/82370293/121499616-d85f1f00-c9dd-11eb-8b11-95fab686675f.png)

#### Tasks

- [x] Work on the design reviews!
- [ ] Review other designs!
- [x] Find a nice navigation solution (maybe burger menu 🧐)
- [x] Be happy and self-confident with your own design 🙂.
