### ISSUE TITLE
"Garden" page

### ISSUE THREAD

**Issue by MaxMuecket** [MaxMuecket/pocket-garden#5]
#### Description

On this page the user  finds a garden full of Options. 

- The `<Link>NewPlant</Link>`brings the user to the "NewPlant" page to create a new plant for his pocket-garden.

![image](https://user-images.githubusercontent.com/82370293/121501283-5f60c700-c9df-11eb-8242-b1e1d22db2bc.png)

- The `<Link>PlantList</Link>`brings the user to the "PlantList" page to see all his created plans for his pocket-garden.

![image](https://user-images.githubusercontent.com/82370293/121501317-68ea2f00-c9df-11eb-9d13-dcd01eb92bb0.png)

- The `<Link>NewTask</Link>`brings the user to the "NewTask" page to create a new task for his pocket-garden.

![image](https://user-images.githubusercontent.com/82370293/121501409-83240d00-c9df-11eb-9105-723ba0707f04.png)

- The `<Link>Gardening</Link>`brings the user to the "Gardening" page to see all present tasks for his pocket-garden.

![image](https://user-images.githubusercontent.com/82370293/121502423-7522bc00-c9e0-11eb-824d-2c0cf3ea1f68.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/82370293/122016044-f56e6600-cdc0-11eb-83a1-b79dcd436838.png)

#### Tasks

`Components`

- [x] `<Link>NewPlant</Link>`
- [x] `<Link>PlantList</Link>`
- [x] `<Link>NewTask</Link>`
- [x] `<Link>Gardening</Link>`
- [x] Implement Subtitle `component`
