### ISSUE TITLE
"NewPlant" page

### ISSUE THREAD

**Issue by MaxMuecket** [MaxMuecket/pocket-garden#6]
#### Description

The "NewPlant" page gives the user the opportunity to create a new plant for his pocket-garden.
The following options are available for the user:

- Upload an image
- Enter a plant name
- Select the sowing month
- Select a place sunny, half shady or shady
- Select perennial yes or no
- Write a note

#### Screenshots

![image](https://user-images.githubusercontent.com/82370293/121508119-9043fa80-c9e5-11eb-9c8c-d373a644e666.png)

#### Tasks

`Components`

- [ ] Image Upload: ???
- [ ] Plant name: `<Input></input>` 
- [ ] Sowing: `<button>{month}</button>`
- [ ] Place: `<button>{place}</button>`
- [ ] Perennial: `<button></button>`
- [ ] Note: `<Input></input>`
