### ISSUE TITLE
"NewTask" page

### ISSUE THREAD

**Issue by MaxMuecket** [MaxMuecket/pocket-garden#9]
#### Description

The user has the possibility to create a new task on this page.
The following options are available for the user:

 - Create a title for the task
 - Describe the task
 - Add a date
 
and in the end, touch/click the create `button`to send up the form.

#### Screenshots

![image](https://user-images.githubusercontent.com/82370293/121539523-09ebe080-ca06-11eb-9f31-e1dabee571a3.png)

#### Tasks

`Components`

- [x] `<input>title</input>`
- [x] `<input>Description...</input>`
- [x] `<input>Date</input>`
- [x] `<button>create</button>`
- [x] `form`
